# Generated by Django 5.0.1 on 2024-02-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachTicketBooking', '0007_remove_feedback_user_feedback_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='trip',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='CoachTicketBooking.trip'),
            preserve_default=False,
        ),
    ]
