# Generated by Django 5.0.1 on 2024-02-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachTicketBooking', '0008_alter_feedback_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
