# Generated by Django 5.0.1 on 2024-02-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoachTicketBooking', '0009_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketseller',
            name='status',
        ),
    ]
