# Generated by Django 5.0.1 on 2024-02-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoachTicketBooking', '0010_remove_ticketseller_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
